.PHONY: clean All

All:
	@echo "----------Building project:[ Railway - Debug ]----------"
	@cd "Railway" && $(MAKE) -f  "Railway.mk"
clean:
	@echo "----------Cleaning project:[ Railway - Debug ]----------"
	@cd "Railway" && $(MAKE) -f  "Railway.mk" clean
