.PHONY: clean All

All:
	@echo "----------Building project:[ Grocery - Debug ]----------"
	@cd "Grocery" && $(MAKE) -f  "Grocery.mk"
clean:
	@echo "----------Cleaning project:[ Grocery - Debug ]----------"
	@cd "Grocery" && $(MAKE) -f  "Grocery.mk" clean
