.PHONY: clean All

All:
	@echo "----------Building project:[ NestedStructure - Debug ]----------"
	@cd "NestedStructure" && $(MAKE) -f  "NestedStructure.mk"
clean:
	@echo "----------Cleaning project:[ NestedStructure - Debug ]----------"
	@cd "NestedStructure" && $(MAKE) -f  "NestedStructure.mk" clean
